version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: 1235813
      POSTGRES_USER: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  consul:
    image: consul:1.15
    ports:
      - "8500:8500"

  user-service:
    build: ./services/user
    environment:
      - DB_HOST=postgres
      - CONSUL_HTTP_ADDR=http://consul:8500
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started

  product-service:
    build: ./services/product
    environment:
      - DB_HOST=postgres
      - CONSUL_HTTP_ADDR=http://consul:8500
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started

  order-service:
    build: ./services/order
    environment:
      - DB_HOST=postgres
      - CONSUL_HTTP_ADDR=http://consul:8500
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started

  payment-service:
    build: ./services/payment
    environment:
      - DB_HOST=postgres
      - CONSUL_HTTP_ADDR=http://consul:8500
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started

  inventory-service:
    build: ./services/inventory
    environment:
      - DB_HOST=postgres
      - CONSUL_HTTP_ADDR=http://consul:8500
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started

  gateway:
    build: ./gateway
    ports:
      - "8081:8081"
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    depends_on:
      - consul
      - user-service
      - product-service
      - order-service
      - payment-service
      - inventory-service

volumes:
  postgres_data: